"""Initial migration

Revision ID: a542632a835f
Revises: 
Create Date: 2026-07-13 11:27:07.645683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a542632a835f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=False),
    sa.Column('slack_username', sa.String(length=100), nullable=False),
    sa.Column('marsos_email', sa.String(length=255), nullable=False),
    sa.Column('marsos_employee_id', sa.String(length=50), nullable=False),
    sa.Column('marsos_password_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_marsos_email'), 'employees', ['marsos_email'], unique=True)
    op.create_index(op.f('ix_employees_marsos_employee_id'), 'employees', ['marsos_employee_id'], unique=True)
    op.create_index(op.f('ix_employees_slack_user_id'), 'employees', ['slack_user_id'], unique=True)
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('slack_event_id', sa.String(length=100), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_date'), 'attendance_logs', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_logs_employee_id'), 'attendance_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_slack_event_id'), 'attendance_logs', ['slack_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_logs_slack_event_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_employee_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_date'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_employees_slack_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_marsos_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_marsos_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
